config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :reviews
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_product)


  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

  scope :most_recent, -> { order(created_at: :desc).limit(3)}

  scope :country_of_origin, -> (country_of_origin_parameter) { where(country_of_origin: "USA") }

  private
  def titleize_product
    self.name = self.name.titleize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates :content_body, length: { in: 50..250 }
  validates :rating, numericality: { only_integer: true,  less_than_or_equal_to_5: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully created!"
      redirect_to products_path
    else
      flash[:notice] = "Product was not created!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    if params[:most_recent]
      @products = @products.most_recent(params[:most_recent])
    else
      @product = Product.find(params[:id])
    end 
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
    flash[:alert] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
          flash[:notice] = "You've deleted this product!"
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:alert] = "Review successfully created!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Review was not created!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>
<div class="form">
  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <br>
    <%= f.label :cost %>
    <%= f.text_field :cost %>
    <br>
    <br>
    <br>
    <%= f.label :country_of_origin %>
    <%= f.text_field :country_of_origin %>
    <p><%= f.submit  %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreDatabase</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <%= yield %>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<div class="title">
  <h1>Mario's Specialty Appliances</h1>
</div>

<div class="product_listing">
<h1>Products</h1>
<p><%= link_to "Create new product", new_product_path %></p>
<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= @product.cost %></h3>
<h3><%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %></h1>
<h2>Review by: <%= @review.author %></h2>
<h3>Rating: <%= @review.rating %> / 5</h3>
<h3><%= @review.content_body %></h3>

<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>